# Generated by Django 5.0 on 2024-05-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(max_length=255, verbose_name='Электронный адрес (email)')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема письма')),
                ('content', models.TextField(verbose_name='Содержимое письма')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP отправителя')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
                'db_table': 'feedback',
                'ordering': ['-time_create'],
            },
        ),
    ]
