# Generated by Django 5.0 on 2024-05-21 09:54

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories_images', verbose_name='Изображение')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='goods.categories', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'category',
                'unique_together': {('parent', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('image_small', models.ImageField(blank=True, null=True, upload_to='goods_images', verbose_name='Изображение для католога')),
                ('image_big', models.ImageField(blank=True, null=True, upload_to='goods_images', verbose_name='Изображение для карточки товара')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание для товара в каталоге')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Цена')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('advantages', models.TextField(blank=True, null=True, verbose_name='Преимущества (ENTER)')),
                ('release_form', models.CharField(blank=True, max_length=150, null=True, verbose_name='Форма выпуска')),
                ('packing', models.CharField(blank=True, max_length=150, null=True, verbose_name='Упаковка')),
                ('nutritional_info', models.TextField(blank=True, null=True, verbose_name='Питательность хар-ки (; ENTER)')),
                ('composition', models.TextField(blank=True, null=True, verbose_name='Состав (ENTER)')),
                ('feeding_standards', models.TextField(blank=True, null=True, verbose_name='Нормы кормления (ENTER) для комбикорма/(; ENTER) для БМВД')),
                ('recommendations', models.TextField(blank=True, null=True, verbose_name='Рекомендации (ENTER)')),
                ('category', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='goods.categories', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'db_table': 'product',
                'ordering': ('id',),
            },
        ),
    ]
